description: The following analytic identifies the assignment of the Application Administrator
  role to an Azure AD user. It leverages Azure Active Directory events, specifically
  monitoring the "Add member to role" operation. This activity is significant because
  users in this role can manage all aspects of enterprise applications, including
  credentials, which can be used to impersonate application identities. If confirmed
  malicious, an attacker could escalate privileges, manage application settings, and
  potentially access sensitive resources by impersonating application identities,
  posing a significant security risk to the Azure AD tenant.
required_fields:
- _time
- user
- properties.targetResources{}.type
- properties.initiatedBy.user.userPrincipalName
- properties.result
rule: sourcetype=azure:monitor:aad  "operationName"="Add member to role"  "properties.targetResources{}.modifiedProperties{}.newValue"="\"Application
  Administrator\"" | rename properties.* as * | rename initiatedBy.user.userPrincipalName
  as initiatedBy | stats count min(_time) as firstTime max(_time) as lastTime by user
  initiatedBy, result, operationName | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `azure_ad_application_administrator_role_assigned_filter`
