description: The following analytic identifies instances where a user grants consent
  to an application requesting mail-related permissions within the Office 365 environment.
  It leverages O365 audit logs, specifically focusing on events related to application
  permissions and user consent actions. This activity is significant as it can indicate
  potential security risks, such as data exfiltration or spear phishing, if malicious
  applications gain access. If confirmed malicious, this could lead to unauthorized
  data access, email forwarding, or sending malicious emails from the compromised
  account. Validating the legitimacy of the application and consent context is crucial
  to prevent data breaches.
required_fields:
- _time
- Workload
- Operation
- ResultStatus
- ModifiedProperties{}.NewValue
- object
- ObjectId
rule: 'sourcetype=o365:management:activity Workload=AzureActiveDirectory Operation="Consent
  to application." ResultStatus=Success | eval admin_consent =mvindex(''ModifiedProperties{}.NewValue'',
  0) | search admin_consent=False | eval permissions =mvindex(''ModifiedProperties{}.NewValue'',
  4) | rex field=permissions "Scope: (?<Scope>[^,]+)" | makemv delim=" " Scope | search
  Scope IN ("Mail.Read", "Mail.ReadBasic", "Mail.ReadWrite", "Mail.Read.Shared", "Mail.ReadWrite.Shared",
  "Mail.Send", "Mail.Send.Shared") | stats max(_time) as lastTime values(Scope) by
  Operation, user, object, ObjectId | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)
  | `o365_mail_permissioned_application_consent_granted_by_user_filter`'
