description: The following analytic identifies the configuration of Azure Active Directory
  Applications in a manner that allows authentication from external tenants or personal
  accounts. This configuration can lead to inappropriate or malicious access of any
  data or capabilities the application is allowed to access. This detection leverages
  the O365 Universal Audit Log data source.
required_fields:
- _time
- Operation
- ModifiedProperties{}.NewValue
- ModifiedProperties{}.Name
- UserId
- Workload
- Target{}.ID
rule: sourcetype=o365:management:activity Workload=AzureActiveDirectory Operation
  IN ("Add application.","Update application.") ModifiedProperties{}.Name=AvailableToOtherTenants
  | eval result = case(match(mvindex('ModifiedProperties{}.NewValue',mvfind('ModifiedProperties{}.Name',"AvailableToOtherTenants")),"false"),"removed",true(),"added"),
  object_name=mvindex('Target{}.ID', 3), signature=Operation, object_attrs = "AvailableToOtherTenants",
  user = case(match(mvindex('Actor{}.ID',-1),"User"),mvindex('Actor{}.ID',0),match(mvindex('Actor{}.ID',-1),"ServicePrincipal"),mvindex('Actor{}.ID',3),true(),mvindex('Actor{}.ID',0))
  | search result = "added" | stats values(ActorIpAddress) as src, count, min(_time)
  as firstTime, max(_time) as lastTime by signature, user, object, object_name, object_attrs,
  result | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)  | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `o365_application_available_to_other_tenants_filter`
