description: The following analytic detects the execution of a suspicious `bcdedit`
  command that configures a host to boot in safe mode with network support. It leverages
  data from Endpoint Detection and Response (EDR) agents, focusing on command-line
  executions involving `bcdedit.exe` with specific parameters. This activity is significant
  because it is a known technique used by BlackMatter ransomware to force a compromised
  host into safe mode for continued encryption. If confirmed malicious, this could
  allow attackers to bypass certain security controls, persist in the environment,
  and continue their malicious activities.
required_fields:
- _time
- Processes.process_name
- Processes.process
- Processes.parent_process_name
- Processes.parent_process
- Processes.dest
- Processes.user
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.process_name = bcdedit.exe Processes.process="*/set*"
  Processes.process="*{current}*"  Processes.process="*safeboot*" Processes.process="*network*"
  by Processes.process_name Processes.process Processes.parent_process_name Processes.dest
  Processes.user |`drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `change_to_safe_mode_with_network_config_filter`'
