description: The following analytic detects executions of cmd.exe spawned by processes
  that are commonly abused by attackers and do not typically launch cmd.exe. It leverages
  data from Endpoint Detection and Response (EDR) agents, focusing on process GUID,
  process name, parent process, and command-line executions. This activity is significant
  because it may indicate an attempt to execute unauthorized commands or scripts,
  often a precursor to further malicious actions. If confirmed malicious, this behavior
  could lead to unauthorized code execution, privilege escalation, or persistence
  within the environment.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count values(Processes.process) as process min(_time)
  as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where (Processes.process_name=cmd.exe
  OR Processes.original_file_name=Cmd.Exe) by Processes.parent_process_name Processes.process_name
  Processes.original_file_name Processes.dest Processes.user| `drop_dm_object_name(Processes)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)| convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) |search [| inputlookup prohibited_apps_launching_cmd | rename prohibited_applications
  as parent_process_name | eval parent_process_name="*" . parent_process_name | table
  parent_process_name] | `detect_prohibited_applications_spawning_cmd_exe_filter`'
