description: The following analytic identifies the rapid execution of processes used
  for system network configuration discovery on an endpoint. It leverages data from
  Endpoint Detection and Response (EDR) agents, focusing on process GUIDs, names,
  parent processes, and command-line executions. This activity is significant as it
  may indicate an attacker attempting to map the network, which is a common precursor
  to lateral movement or further exploitation. If confirmed malicious, this behavior
  could allow an attacker to gain insights into the network topology, identify critical
  systems, and plan subsequent attacks, potentially leading to data exfiltration or
  system compromise.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count values(Processes.process) as process values(Processes.parent_process)
  as parent_process min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes
  where NOT Processes.user IN ("","unknown") by Processes.dest Processes.process_name
  Processes.parent_process_name Processes.user _time | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `drop_dm_object_name(Processes)`
  | search (process_name= "arp.exe" OR process_name= "at.exe" OR process_name= "attrib.exe"
  OR process_name= "cscript.exe" OR process_name= "dsquery.exe" OR process_name= "hostname.exe"
  OR process_name= "ipconfig.exe" OR process_name= "mimikatz.exe" OR process_name=
  "nbstat.exe" OR process_name= "net.exe" OR process_name= "netsh.exe" OR process_name=
  "nslookup.exe" OR process_name= "ping.exe" OR process_name= "quser.exe" OR process_name=
  "qwinsta.exe" OR process_name= "reg.exe" OR process_name= "runas.exe" OR process_name=
  "sc.exe" OR process_name= "schtasks.exe" OR process_name= "ssh.exe" OR process_name=
  "systeminfo.exe" OR process_name= "taskkill.exe" OR process_name= "telnet.exe" OR
  process_name= "tracert.exe" OR process_name="wscript.exe" OR process_name= "xcopy.exe")
  | transaction dest connected=false maxpause=5m |where eventcount>=5 | table firstTime
  lastTime dest user process_name process parent_process parent_process_name eventcount
  | `detect_processes_used_for_system_network_configuration_discovery_filter`'
