description: The following analytic detects the execution of rundll32.exe loading
  setupapi.dll and iesetupapi.dll via the LaunchINFSection function. This behavior
  is identified using Endpoint Detection and Response (EDR) telemetry, focusing on
  process creation events and command-line arguments. This activity is significant
  as it indicates a potential application control bypass, allowing an attacker to
  execute arbitrary script code. If confirmed malicious, this technique could enable
  code execution, privilege escalation, or persistence within the environment, posing
  a severe threat to system integrity and security.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where (Processes.process_name=rundll32.exe OR
  Processes.original_file_name=RUNDLL32.EXE) Processes.process=*setupapi* by Processes.dest
  Processes.user Processes.parent_process_name Processes.original_file_name Processes.process_name
  Processes.process Processes.process_id Processes.parent_process_id | `drop_dm_object_name(Processes)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `detect_rundll32_application_control_bypass___setupapi_filter`'
