description: The following analytic detects modifications to the registry that disable
  the CMD prompt application. It leverages data from the Endpoint.Registry data model,
  specifically looking for changes to the "DisableCMD" registry value. This activity
  is significant because disabling CMD can hinder an analyst's ability to investigate
  and remediate threats, a tactic often used by malware such as RATs, Trojans, or
  Worms. If confirmed malicious, this could prevent security teams from using CMD
  for directory and file traversal, complicating incident response and allowing the
  attacker to maintain persistence.
required_fields:
- _time
- Registry.dest
- Registry.registry_value_name
- Registry.registry_key_name
- Registry.registry_path
- Registry.registry_value_data
- Registry.process_guid
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  FROM datamodel=Endpoint.Registry WHERE (Registry.registry_path= "*\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DisableCMD"
  Registry.registry_value_data = "0x00000001") BY Registry.dest Registry.user Registry.registry_path
  Registry.registry_key_name Registry.registry_value_name Registry.registry_value_data
  Registry.process_guid | `drop_dm_object_name(Registry)` | where isnotnull(registry_value_data)
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `disabling_cmd_application_filter`'
