description: The following analytic detects the use of 'curl' and 'wget' commands
  within a Linux environment. It leverages data from Endpoint Detection and Response
  (EDR) agents, focusing on process names, user information, and command-line executions.
  This activity is significant as 'curl' and 'wget' are commonly used for downloading
  files, which can indicate potential ingress of malicious tools. If confirmed malicious,
  this activity could lead to unauthorized code execution, data exfiltration, or further
  compromise of the system. Monitoring and tuning this detection helps identify and
  differentiate between normal and potentially harmful usage.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where (Processes.process_name=curl OR Processes.process_name=wget)
  by Processes.dest Processes.user Processes.parent_process_name Processes.process_name
  Processes.process Processes.process_id Processes.parent_process_id | `drop_dm_object_name(Processes)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `linux_ingress_tool_transfer_hunting_filter`'
