description: The following analytic detects the execution of the Composer tool with
  elevated privileges on a Linux system. It identifies instances where Composer is
  run with the 'sudo' command, allowing the user to execute system commands as root.
  This detection leverages data from Endpoint Detection and Response (EDR) agents,
  focusing on process execution logs and command-line arguments. This activity is
  significant because it can indicate an attempt to escalate privileges, potentially
  leading to unauthorized root access. If confirmed malicious, an attacker could gain
  full control over the system, execute arbitrary commands, and compromise sensitive
  data.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.process="*composer*" AND Processes.process="*run-script*"
  AND Processes.process="*sudo*" by Processes.dest Processes.user Processes.parent_process_name
  Processes.process_name Processes.process Processes.process_id Processes.parent_process_id
  Processes.process_guid | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `linux_composer_privilege_escalation_filter`'
