description: The following analytic detects the execution of the "At" application
  in Linux, which can be used by attackers to create persistence entries on a compromised
  host. This detection leverages data from Endpoint Detection and Response (EDR) agents,
  focusing on process names and parent process names associated with "at" or "atd".
  This activity is significant because the "At" application can be exploited to maintain
  unauthorized access or deliver additional malicious payloads. If confirmed malicious,
  this behavior could lead to data theft, ransomware attacks, or other severe consequences.
  Immediate investigation is required to determine the legitimacy of the execution
  and mitigate potential risks.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count from datamodel=Endpoint.Processes where  Processes.process_name
  IN ("at", "atd") OR Processes.parent_process_name IN ("at", "atd") by Processes.dest
  Processes.user Processes.parent_process_name Processes.process_name Processes.process
  Processes.process_id Processes.parent_process_id Processes.process_guid | `drop_dm_object_name(Processes)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `linux_at_application_execution_filter`'
