description: The following analytic detects suspicious command lines that append user
  entries to /etc/at.allow or /etc/at.deny files. It leverages data from Endpoint
  Detection and Response (EDR) agents, focusing on command-line executions involving
  these files. This activity is significant because altering these configuration files
  can allow attackers to schedule tasks with elevated permissions, facilitating persistence
  on a compromised Linux host. If confirmed malicious, this could enable attackers
  to execute arbitrary code at scheduled intervals, potentially leading to further
  system compromise and unauthorized access to sensitive information.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count from datamodel=Endpoint.Processes where Processes.process
  = "*echo*" AND Processes.process IN("*/etc/at.allow", "*/etc/at.deny") by Processes.dest
  Processes.user Processes.parent_process_name Processes.process_name Processes.process
  Processes.process_id Processes.parent_process_id Processes.process_guid | `drop_dm_object_name(Processes)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `linux_possible_append_command_to_at_allow_config_file_filter`'
