description: The following analytic detects suspicious command-lines that modify user
  profile files to automatically execute scripts or executables upon system reboot.
  It leverages data from Endpoint Detection and Response (EDR) agents, focusing on
  command-line executions involving profile files like ~/.bashrc and /etc/profile.
  This activity is significant as it indicates potential persistence mechanisms used
  by adversaries to maintain access to compromised hosts. If confirmed malicious,
  this could allow attackers to execute arbitrary code upon reboot, leading to persistent
  control over the system and potential further exploitation.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.process = "*echo*" AND Processes.process
  IN("*~/.bashrc", "*~/.bash_profile", "*/etc/profile", "~/.bash_login", "*~/.profile",
  "~/.bash_logout") by Processes.dest Processes.user Processes.parent_process_name
  Processes.process_name Processes.process Processes.process_id Processes.parent_process_id
  Processes.process_guid | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `linux_possible_append_command_to_profile_config_file_filter`'
