description: The following analytic detects the creation of the /etc/at.allow or /etc/at.deny
  configuration files in Linux. It leverages file creation events from the Endpoint
  datamodel to identify when these files are created. This activity is significant
  as these files control user permissions for the "at" scheduling application and
  can be abused by attackers to establish persistence. If confirmed malicious, this
  could allow unauthorized execution of malicious code, leading to potential data
  theft or further system compromise. Analysts should review the file path, creation
  time, and associated processes to assess the threat.
required_fields:
- _time
- Filesystem.dest
- Filesystem.file_create_time
- Filesystem.file_name
- Filesystem.process_guid
- Filesystem.file_path
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  FROM datamodel=Endpoint.Filesystem where Filesystem.file_path IN ("*/etc/at.allow",
  "*/etc/at.deny") by Filesystem.dest Filesystem.file_create_time Filesystem.file_name
  Filesystem.process_guid Filesystem.file_path | `drop_dm_object_name(Filesystem)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `linux_at_allow_config_file_creation_filter`'
