description: The following analytic detects suspicious access or modification of the
  sshd_config file on Linux systems. It leverages data from Endpoint Detection and
  Response (EDR) agents, focusing on command-line executions involving processes like
  "cat," "nano," "vim," and "vi" accessing the sshd_config file. This activity is
  significant because unauthorized changes to sshd_config can allow threat actors
  to redirect port connections or use unauthorized keys, potentially compromising
  the system. If confirmed malicious, this could lead to unauthorized access, privilege
  escalation, or persistent backdoor access, posing a severe security risk.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.process_name IN("cat", "nano*","vim*",
  "vi*")  AND Processes.process IN("*/etc/ssh/sshd_config") by Processes.dest Processes.user
  Processes.parent_process_name Processes.process_name Processes.process Processes.process_id
  Processes.parent_process_id | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `linux_possible_access_or_modification_of_sshd_config_file_filter`'
