description: The following analytic identifies processes referencing plist files that
  determine which applications are re-opened when a user reboots their MacOS machine.
  It leverages data from Endpoint Detection and Response (EDR) agents, focusing on
  process names and parent processes related to "com.apple.loginwindow." This activity
  is significant because it can indicate attempts to persist across reboots, a common
  tactic used by attackers to maintain access. If confirmed malicious, this could
  allow an attacker to execute code or maintain persistence on the affected system,
  potentially leading to further compromise.
required_fields:
- _time
- Processes.process
- Processes.parent_process
- Processes.user
- Processes.process_name
- Processes.parent_process_name
- Processes.dest
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count values(Processes.process) as process values(Processes.parent_process)
  as parent_process min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes
  where Processes.process="*com.apple.loginwindow*" by Processes.user Processes.process_name
  Processes.parent_process_name Processes.dest | `drop_dm_object_name(Processes)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `macos___re_opened_applications_filter`'
