description: The following analytic detects the suspicious creation of msmpeng.exe
  or mpsvc.dll in non-default Windows Defender folders. It leverages the Endpoint.Filesystem
  datamodel to identify instances where these files are created outside their expected
  directories. This activity is significant because it is associated with the REvil
  ransomware, which uses DLL side-loading to execute malicious payloads. If confirmed
  malicious, this could lead to ransomware deployment, resulting in data encryption,
  system compromise, and potential data loss or extortion.
required_fields:
- _time
- Filesystem.file_create_time
- Filesystem.process_id
- Filesystem.file_name
- Filesystem.user
- Filesystem.file_path
rule: '|tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` values(Filesystem.file_path) as file_path count
  min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Filesystem
  where (Filesystem.file_name = "msmpeng.exe" OR Filesystem.file_name = "mpsvc.dll")  AND
  NOT (Filesystem.file_path IN ("*\\Program Files\\windows defender\\*","*\\WinSxS\\*defender-service*","*\\WinSxS\\Temp\\*defender-service*"))
  by Filesystem.file_create_time Filesystem.process_id  Filesystem.file_name Filesystem.user
  Filesystem.dest | `drop_dm_object_name(Filesystem)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `msmpeng_application_dll_side_loading_filter`'
