description: The following analytic identifies instances where an Office application
  spawns a Regsvr32 process, which is often indicative of macro execution or malicious
  code. This detection leverages data from Endpoint Detection and Response (EDR) agents,
  focusing on process creation events where the parent process is a known Office application.
  This activity is significant because it is a common technique used by malware, such
  as IcedID, to initiate infections. If confirmed malicious, this behavior could lead
  to code execution, allowing attackers to gain control over the affected system and
  potentially escalate privileges.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where (Processes.parent_process_name = "winword.exe"
  OR Processes.parent_process_name = "excel.exe" OR Processes.parent_process_name
  = "powerpnt.exe" OR Processes.parent_process_name = "outlook.exe" OR Processes.parent_process_name
  = "onenote.exe" OR Processes.parent_process_name = "onenotem.exe" OR Processes.parent_process_name
  = "onenoteviewer.exe" OR Processes.parent_process_name = "onenoteim.exe" OR Processes.parent_process_name="msaccess.exe")
  (Processes.process_name=regsvr32.exe OR Processes.original_file_name=REGSVR32.EXE)
  by Processes.parent_process_name Processes.parent_process Processes.process_name
  Processes.original_file_name Processes.process Processes.process_id Processes.process_guid
  Processes.user Processes.dest | `drop_dm_object_name("Processes")` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) |convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `office_application_spawn_regsvr32_process_filter`'
