description: The following analytic detects Microsoft Office applications dropping
  or creating executables or scripts on a Windows OS. It leverages process creation
  and file system events from the Endpoint data model to identify Office applications
  like Word or Excel generating files with extensions such as .exe, .dll, or .ps1.
  This behavior is significant as it is often associated with spear-phishing attacks
  where malicious files are dropped to compromise the host. If confirmed malicious,
  this activity could lead to code execution, privilege escalation, or persistent
  access, posing a severe threat to the environment.
required_fields:
- _time
- process_name
- file_name
- process_guid
- dest
- user_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count FROM datamodel=Endpoint.Processes where Processes.process_name
  IN ("winword.exe","excel.exe","powerpnt.exe","mspub.exe","visio.exe","wordpad.exe","wordview.exe","onenote.exe","onenotem.exe","onenoteviewer.exe","onenoteim.exe","msaccess.exe")
  by _time span=1h Processes.process_id Processes.process_name Processes.process Processes.dest
  Processes.process_guid | `drop_dm_object_name(Processes)` |join process_guid, _time
  [| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  FROM datamodel=Endpoint.Filesystem where Filesystem.file_name IN ("*.exe","*.dll","*.pif","*.scr","*.js","*.vbs","*.vbe","*.ps1")
  by _time span=1h Filesystem.dest Filesystem.file_create_time Filesystem.file_name
  Filesystem.process_guid Filesystem.file_path | `drop_dm_object_name(Filesystem)`
  | fields _time dest file_create_time file_name file_path process_name process_path
  process process_guid] | dedup file_create_time | table dest, process_name, process,
  file_create_time, file_name, file_path, process_guid | `office_application_drop_executable_filter`'
