description: The following analytic detects the execution of the sdelete.exe application,
  a Sysinternals tool often used by adversaries to securely delete files and remove
  forensic evidence from a targeted host. This detection leverages data from Endpoint
  Detection and Response (EDR) agents, focusing on process execution logs. Monitoring
  this activity is crucial as sdelete.exe is not commonly used in regular operations
  and its presence may indicate an attempt to cover malicious activities. If confirmed
  malicious, this could lead to the loss of critical forensic data, hindering incident
  response and investigation efforts.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` values(Processes.process) as process values(Processes.parent_process)
  as parent_process values(Processes.process_id) as process_id count min(_time) as
  firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where (Processes.process_name=sdelete.exe
  OR Processes.original_file_name=sdelete.exe) by  Processes.process_name Processes.original_file_name
  Processes.dest Processes.user Processes.parent_process_name Processes.parent_process
  | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `sdelete_application_execution_filter`'
