description: The following analytic detects modifications in the Windows registry
  to disable Windows Error Reporting (WER) settings. It leverages data from the Endpoint.Registry
  datamodel, specifically monitoring changes to registry paths related to WER with
  a value set to "0x00000001". This activity is significant as adversaries may disable
  WER to suppress error notifications, hiding the presence of malicious activities.
  If confirmed malicious, this could allow attackers to operate undetected, potentially
  leading to prolonged persistence and further exploitation within the environment.
required_fields:
- _time
- Registry.registry_key_name
- Registry.registry_path
- Registry.user
- Registry.dest
- Registry.registry_value_name
- Registry.action
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  FROM datamodel=Endpoint.Registry where Registry.registry_path= "*\\SOFTWARE\\Microsoft\\Windows\\Windows
  Error Reporting\\disable*" Registry.registry_value_data="0x00000001" by Registry.registry_key_name
  Registry.user Registry.registry_path Registry.registry_value_data Registry.action
  Registry.dest | `drop_dm_object_name(Registry)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `windows_modify_registry_disabling_wer_settings_filter`'
