description: The following analytic detects modifications to the Windows registry
  that disable the Windows Defender SmartScreen App Install Control feature. It leverages
  data from the Endpoint.Registry data model to identify changes to specific registry
  values. This activity is significant because disabling App Install Control can allow
  users to install potentially malicious web-based applications without restrictions,
  increasing the risk of security vulnerabilities. If confirmed malicious, this action
  could lead to the installation of harmful applications, potentially compromising
  the system and exposing sensitive information.
required_fields:
- _time
- Registry.registry_key_name
- Registry.registry_value_name
- Registry.dest
- Registry.user
- Registry.registry_path
- Registry.action
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  FROM datamodel=Endpoint.Registry WHERE (Registry.registry_path= "*\\Microsoft\\Windows
  Defender\\SmartScreen\\ConfigureAppInstallControl" Registry.registry_value_data=
  "Anywhere") OR (Registry.registry_path= "*\\Microsoft\\Windows Defender\\SmartScreen\\ConfigureAppInstallControlEnabled"
  Registry.registry_value_data= "0x00000000") BY Registry.dest Registry.user Registry.registry_path
  Registry.registry_key_name Registry.registry_value_name Registry.registry_value_data
  Registry.process_guid | `drop_dm_object_name(Registry)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `windows_impair_defense_configure_app_install_control_filter`'
