description: The following analytic detects modifications to the Windows registry
  that disable security settings for Terminal Services. It leverages the Endpoint
  data model, specifically monitoring changes to the registry path associated with
  Terminal Services security settings. This activity is significant because altering
  these settings can weaken the security posture of Remote Desktop Services, potentially
  allowing unauthorized remote access. If confirmed malicious, such modifications
  could enable attackers to gain persistent remote access to the system, facilitating
  further exploitation and data exfiltration.
required_fields:
- _time
- Registry.registry_key_name
- Registry.registry_path
- Registry.user
- Registry.dest
- Registry.registry_value_name
- Registry.action
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Registry where Registry.registry_path = "*\\Terminal Services\\DisableSecuritySettings"  Registry.registry_value_data
  = 0x00000001 by  Registry.registry_path Registry.registry_value_name Registry.registry_value_data
  Registry.process_guid Registry.action Registry.user Registry.dest | `drop_dm_object_name(Registry)`
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `windows_modify_registry_disablesecuritysettings_filter`'
