description: The following analytic detects the execution of a suspicious rundll32
  command line that updates user-specific system parameters, such as desktop backgrounds,
  display settings, and visual themes. It leverages data from Endpoint Detection and
  Response (EDR) agents, focusing on command-line executions involving "user32.dll,UpdatePerUserSystemParameters."
  This activity is significant as it is uncommon for legitimate purposes and has been
  observed in Rhysida Ransomware for defense evasion. If confirmed malicious, this
  could allow an attacker to disguise activities or make unauthorized system changes,
  potentially leading to persistent unauthorized access.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process
- Processes.parent_process_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.process_name=rundll32.exe Processes.process=
  "*user32.dll,UpdatePerUserSystemParameters*" by Processes.dest Processes.user Processes.parent_process
  Processes.process_name Processes.process Processes.process_id Processes.parent_process_id
  Processes.parent_process_name | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `windows_rundll32_apply_user_settings_changes_filter`'
