description: The following analytic identifies the execution of the "ipconfig /displaydns"
  command, which retrieves DNS reply information using the built-in Windows tool IPConfig.
  This detection leverages data from Endpoint Detection and Response (EDR) agents,
  focusing on process command-line executions. Monitoring this activity is significant
  as threat actors and post-exploitation tools like WINPEAS often abuse this command
  to gather network information. If confirmed malicious, this activity could allow
  attackers to map the network, identify DNS servers, and potentially facilitate further
  network-based attacks or lateral movement.
required_fields:
- _time
- Processes.dest
- Processes.user
- Processes.parent_process_name
- Processes.parent_process
- Processes.original_file_name
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_path
- Processes.process_path
- Processes.parent_process_id
- Processes.parent_process_guid
- Processes.process_guid
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.process_name="ipconfig.exe" OR
  Processes.original_file_name = "ipconfig.exe" AND Processes.process = "*/displaydns*"
  by Processes.process_name Processes.original_file_name Processes.process Processes.process_id
  Processes.process_guid Processes.parent_process_name Processes.parent_process Processes.parent_process_guid
  Processes.dest Processes.user | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `windows_system_network_config_discovery_display_dns_filter`'
