description: The following analytic detects a suspicious process accessing the registry
  entries for default internet browsers. It leverages Windows Security Event logs,
  specifically event code 4663, to identify access attempts to these registry paths.
  This activity is significant because adversaries can exploit this registry key to
  gather information about installed browsers and their settings, potentially leading
  to the theft of sensitive data such as login credentials and browsing history. If
  confirmed malicious, this behavior could enable attackers to exfiltrate sensitive
  information and compromise user accounts.
required_fields:
- _time
- object_file_name
- object_file_path
- process_name
- process_path
- process_id
- EventCode
- dest
rule: eventtype=wineventlog_security OR Channel=security OR source=XmlWinEventLog:Security
  EventCode=4663 object_file_path IN ("*\\SOFTWARE\\Clients\\StartMenuInternet\\*",
  "*\\SOFTWARE\\Clients\\StartMenuInternet\\*") AND NOT (process_path IN ("*:\\Windows\\System32\\*",
  "*:\\Windows\\SysWow64\\*", "*:\\Program Files*", "*:\\Windows\\*")) | stats count
  min(_time) as firstTime max(_time) as lastTime by object_file_name object_file_path
  process_name process_path  process_id EventCode dest | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `windows_query_registry_browser_list_application_filter`
