description: The following analytic detects the use of default or publicly known named
  pipes associated with the RMX remote admin tool. It leverages Sysmon EventCodes
  17 and 18 to identify named pipe creation and connection events. This activity is
  significant as the RMX tool has been abused by adversaries and malware like Azorult
  to collect data from targeted hosts. If confirmed malicious, this could indicate
  unauthorized remote administration capabilities, leading to data exfiltration or
  further compromise of the affected system. Immediate investigation is required to
  determine the legitimacy of this tool's presence.
required_fields:
- _time
- Image
- EventType
- ProcessId
- PipeName
- dest
- UserID
rule: sourcetype=XmlWinEventLog:Microsoft-Windows-Sysmon/Operational OR source=XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
  OR source=Syslog:Linux-Sysmon/Operational EventCode IN (17, 18) EventType IN ( "CreatePipe",
  "ConnectPipe") PipeName IN ("\\RManFUSServerNotify32", "\\RManFUSCallbackNotify32",
  "\\RMSPrint*") | stats  min(_time) as firstTime max(_time) as lastTime count by
  Image EventType ProcessId PipeName dest UserID | rename UserID as user | convert
  timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | convert timeformat="%Y-%m-%dT%H:%M:%S"
  ctime($field$) | `windows_application_layer_protocol_rms_radmin_tool_namedpipe_filter`
