description: The following analytic detects the execution of Windows shell processes
  initiated by WinRAR, such as "cmd.exe", "powershell.exe", "certutil.exe", "mshta.exe",
  or "bitsadmin.exe". This detection leverages data from Endpoint Detection and Response
  (EDR) agents, focusing on process and parent process relationships. This activity
  is significant because it may indicate exploitation of the WinRAR CVE-2023-38831
  vulnerability, where malicious scripts are executed from spoofed ZIP archives. If
  confirmed malicious, this could lead to unauthorized access, financial loss, and
  further malicious activities like data theft or ransomware attacks.
required_fields:
- Processes.dest
- Processes.user
- Processes.parent_process
- Processes.process_name
- Processes.process
- Processes.process_id
- Processes.parent_process_id
rule: '| tstats summariesonly=`summariesonly_config` allow_old_summaries=`oldsummaries_config`
  fillnull_value=`fillnull_config` count min(_time) as firstTime max(_time) as lastTime
  from datamodel=Endpoint.Processes where Processes.parent_process_name=winrar.exe
  (Processes.process_name=cmd.exe OR Processes.process_name=powershell.exe OR Processes.process_name=pwsh.exe
  OR Processes.process_name=sh.exe OR Processes.process_name=bash.exe OR Processes.process_name=wscript.exe
  OR Processes.process_name=cscript.exe) OR Processes.process_name IN ("certutil.exe","mshta.exe","bitsadmin.exe")
  by Processes.dest Processes.user Processes.parent_process_name Processes.parent_process
  Processes.process_name Processes.process Processes.process_id Processes.parent_process_id
  | `drop_dm_object_name(Processes)` | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)
  | convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$) | `winrar_spawning_shell_application_filter`'
